# docker-compose.yml
services:
  zoo1:
    image: zookeeper:3.9
    hostname: zoo1
    container_name: zoo1
    ports:
      - "2181:2181"
      - "8081:8080"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok,stat,srvr,cons,dump,envi,wchs"
      ZOO_LOG_LEVEL: ERROR
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
    networks:
      - zk-net
    restart: on-failure

  zoo2:
    image: zookeeper:3.9
    hostname: zoo2
    container_name: zoo2
    ports:
      - "2182:2181"
      - "8082:8080"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok,stat,srvr,cons,dump,envi,wchs"
      ZOO_LOG_LEVEL: ERROR
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
    networks:
      - zk-net
    restart: on-failure

  zoo3:
    image: zookeeper:3.9
    hostname: zoo3
    container_name: zoo3
    ports:
      - "2183:2181"
      - "8083:8080"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok,stat,srvr,cons,dump,envi,wchs"
      ZOO_LOG_LEVEL: ERROR
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: ERROR
    networks:
      - zk-net
    restart: on-failure

networks:
  zk-net:
    driver: bridge
