# Master node - orchestrates MPI jobs
FROM mpi-mpi-base:latest

LABEL description="OpenMPI Master Node"

# Copy example MPI programs
COPY examples/ /home/mpiuser/mpi_work/examples/
COPY examples/ /home/mpiuser/mpi_work/shared/

# Copy entrypoint and hostfile generation script
COPY scripts/master-entrypoint.sh /usr/local/bin/master-entrypoint.sh
COPY scripts/generate-hostfile.sh /usr/local/bin/generate-hostfile.sh

RUN chmod +x /usr/local/bin/master-entrypoint.sh && \
    chmod +x /usr/local/bin/generate-hostfile.sh && \
    chown -R mpiuser:mpiuser /home/mpiuser/mpi_work

USER mpiuser
WORKDIR /home/mpiuser/mpi_work

# Compile example programs
RUN cd examples && \
    mpicc -o hello_world.elf hello_world.c && \
    mpicc -o pi_calculation.elf pi_calculation.c && \
    mpicc -o ring_communication.elf ring_communication.c && \
    cp *.elf ../shared

USER root

ENTRYPOINT ["/usr/local/bin/master-entrypoint.sh"]
CMD ["bash"]
