# Master node - orchestrates MPI jobs
FROM mpi-base:latest

LABEL description="OpenMPI Master Node"


# Copy entrypoint and hostfile generation script
COPY scripts/master-entrypoint.sh /usr/local/bin/master-entrypoint.sh
COPY scripts/generate-hostfile.sh /usr/local/bin/generate-hostfile.sh

RUN chmod +x /usr/local/bin/master-entrypoint.sh && \
    chmod +x /usr/local/bin/generate-hostfile.sh && \
    chown -R mpiuser:mpiuser /home/mpiuser/mpi_work

USER mpiuser
WORKDIR /home/mpiuser/mpi_work

USER root

ENTRYPOINT ["/usr/local/bin/master-entrypoint.sh"]
CMD ["bash"]
