# Worker node - executes MPI tasks
FROM mpi-base:latest

LABEL description="OpenMPI Worker Node"

COPY scripts/worker-entrypoint.sh /usr/local/bin/worker-entrypoint.sh
COPY scripts/mount-nfs.sh         /usr/local/bin/mount-nfs.sh

RUN chmod +x /usr/local/bin/worker-entrypoint.sh \
             /usr/local/bin/mount-nfs.sh

ENTRYPOINT ["/usr/local/bin/worker-entrypoint.sh"]
