# docker-compose.yml
services:

  zoo1:
    image: zookeeper:3.9
    hostname: zoo1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "2181:2181"     # client port
      - "8080:8080"     # admin HTTP server
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    restart: on-failure

  zoo2:
    image: zookeeper:3.9
    hostname: zoo2
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    restart: on-failure

  zoo3:
    image: zookeeper:3.9
    hostname: zoo3
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=zoo2:2888:3888;2181 server.3=zoo3:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "*"
    restart: on-failure
